version: '3.7'

services:
  my_parser:
    build: ./
    command: python manage.py runserver 0.0.0.0:9020
    # command: django-admin startproject --template=https://github.com/arocks/edge/archive/master.zip --extension=py,md,html,env cv_uploader .
    volumes:
      - ./cv_uploader/:/usr/src/cv_uploader
    ports:
      - 9020:9020
    tty: true
    stdin_open: true
    # env_file:
    #   - ./.env.dev
    depends_on:
      - my_db
  my_db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
volumes:
  postgres_data:
