# Generated by Django 2.0.9 on 2020-02-13 14:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='document',
            field=models.FileField(default=django.utils.timezone.now, upload_to='CVS//%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
